kind: pipeline
type: docker
name: build

platform:
  os: windows
  arch: amd64

trigger:
  branch:
    - main

clone:
  disable: true

steps:
  - name: clone
    image: refringe/spt-build-environment:1.0.0
    commands:
      - git clone https://dev.sp-tarkov.com/SPT-AKI/Build.git C:\Code
      - cd C:\Code
      - git checkout ${DRONE_COMMIT}
    volumes:
      - name: code
        path: C:\Code

  - name: build
    image: refringe/spt-build-environment:1.0.0
    environment:
      MODULE_DOMAIN:
        from_secret: MODULE_DOMAIN
    commands:
      - cd C:\Code
      - pwsh -File C:\Code\project\build.ps1 -Tag "${DRONE_TAG}"
    volumes:
      - name: code
        path: C:\Code

volumes:
  - name: code
    temp: {}
