kind: pipeline
type: docker
name: trigger-spt-build

trigger:
  event:
    - tag

steps:
- name: trigger-build-check
  image: plugins/downstream
  settings:
    repositories:
      - SPT-AKI/Build
    server: https://drone.sp-tarkov.com
    token:
      from_secret: gitea_token
    when:
      event: tag
