name: SPT Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-environment:1.0.3

    steps:
    - name: Checkout Server Project
      run: git clone https://dev.sp-tarkov.com/SPT-AKI/Server.git --branch "3.8.0-BE" --depth 1 "./SPT-AKI/Server"

    - name: Checkout Git LFS Objects
      run: git lfs pull
      working-directory: ./SPT-AKI/Server

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'

    - name: Install Dependencies
      run: npm install
      working-directory: ./project

    - name: Build Project
      run: npm run build
      working-directory: ./project

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: built-artifacts
        path: build
