name: SPT Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-environment:latest

    steps:
    - name: Checkout Server Project
      uses: actions/checkout@v4
      with:
        repository: 'refringe/Server'
        fetch-depth: 0
        lfs: true

    - name: Checkout Git LFS Objects
      run: git lfs checkout

    - name: Setup Node & NPM
      run: nvm use
      working-directory: ./project

    - name: Install dependencies
      run: npm install
      working-directory: ./project

    - name: Build Project
      run: npm run build
      working-directory: ./project

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: built-artifacts
        path: build
