name: SPT Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-environment:1.0.3

    steps:
    - name: Checkout Server Project
      uses: actions/checkout@v4
      with:
        repository: 'refringe/Server'
        path: 'refringe/Server'
        ref: '3.8.0-BE'
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./project/package.json

    - name: Install Dependencies
      run: npm install
      working-directory: ./project

    - name: Build Project
      run: npm run build
      working-directory: ./project

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: built-artifacts
        path: build
