name: SPT Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build Server:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-environment:1.0.5

    steps:
    - name: Server Cache
      id: server-cache
      uses: actions/cache@v4
      with:
        path: /workspace/server
        key: server-${{ gitea.sha }}
        restore-keys: server-

    - name: Clone Server
      if: steps.cache-server-project.outputs.cache-hit != 'true'
      run: git clone https://dev.sp-tarkov.com/SPT-AKI/Server.git --branch 3.8.0-BE --depth 1 /workspace/server

    - name: Pull Server LFS Files
      if: steps.cache-server-project.outputs.cache-hit != 'true'
      run: |
        cd /workspace/server
        git lfs pull && git lfs ls-files
