name: SPT Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-environment:1.0.3

    steps:
    - name: Checkout Server Project
      run: git clone https://dev.sp-tarkov.com/SPT-AKI/Server.git --branch 3.8.0-BE --depth 1 /workspace/server

    - name: Pull LFS Files
      run: git lfs pull
      workspace: /workspace/server
