name: SPT Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-environment:1.0.4

    steps:
    - name: Checkout Server Project
      uses: actions/checkout@v4
      with:
        repository: 'refringe/Server'
        path: 'server'
        ref: '3.8.0-BE'
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./project/package.json
